import { ApiProperty } from '@nestjs/swagger';
import { IsBoolean, IsOptional, IsString, Length, MinLength } from 'class-validator';

export class TotpVerifyDto {
  @ApiProperty({
    description:
      'Short-lived 2FA challenge token returned by POST /auth/login when TOTP is required.',
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXAiOiJ0b3RwIn0.abcdef',
  })
  @IsString()
  @MinLength(8)
  tempToken!: string;

  @ApiProperty({
    description: 'Six-digit TOTP code from the user authenticator app.',
    example: '492817',
  })
  @IsString()
  @Length(6, 8)
  code!: string;

  @ApiProperty({
    description: 'Issue a long-lived refresh token (30 days) instead of the default 7 days.',
    example: false,
    required: false,
  })
  @IsBoolean()
  @IsOptional()
  rememberMe?: boolean;
}

export class TotpEnableDto {
  @ApiProperty({
    description: 'Six-digit TOTP code generated by the authenticator app to confirm setup.',
    example: '492817',
  })
  @IsString()
  @Length(6, 8)
  code!: string;
}
